<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Secretary.Domain</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.*" />
  </ItemGroup>
</Project>
